### ISSUE TITLE
Add auto indexing to profiles and infrustructure .travis.yml 

### ISSUE THREAD

**Issue by kindly** [OpenDataServices/standard-search#9]
This relies on #8 being completed as each profile has own list of indexable languages.

**Comment by kindly** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Document and improve standard-search](https://trello.com/c/31F2W1nd/7-document-and-improve-standard-search)

**Comment by ghost** [comment]
@kindly Is there a list somewhere of which part of the website (profiles and infrustructure, etc) should have which languages translated?

**Comment by kindly** [comment]
@odscjames no.

I think we will just have to look at the particular website and look at the language dropdown there.

**Comment by ghost** [comment]
Discussion:
* We are going to create a LANGS environmental variable that the deploy scripts use. This is because 3 profiles share the same deploy script but have different languages, so this allows the languages to be set per profile.
* The LANGS var will be set in travis.yml directly. This will allow different branches to have different languages.


@kindly Can you review 2 pull requests?

* https://github.com/open-contracting/infrastructure/pull/148
* https://github.com/open-contracting/deploy/pull/4

I have already added the Secret Key to infrastructure repo, so in theory we should just have to merge the above 2 P.R.'s and it should start to work.

If so, I'll make similar pull requests for all the profiles.

**Comment by ghost** [comment]
This has now been done for infrastructure and I have seen results in the API.

Now doing for profiles.

**Comment by ghost** [comment]
Think this is now done?
